apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: uat 
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJlV1YzYVc1MFlYVnVaenBuYUhCZlNEUlRVM0F4UWpaalpFWXhibmxJWlRkeVFURkNVbkZSY2xaT2VIWmtNMDl0UlRCbyIKCQl9Cgl9Cn0=
